# Generated by Django 6.0.2 on 2026-03-03 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=10)),
                ('chapter', models.CharField(choices=[('houston', 'Houston'), ('austin', 'Austin'), ('dallas', 'Dallas')], default='houston', max_length=20)),
                ('kids_ages', models.CharField(help_text='Comma-separated ages, e.g. 3, 7, 11', max_length=100)),
                ('needs', models.TextField(blank=True, help_text='What kind of help do you need?')),
                ('offers', models.TextField(blank=True, help_text='What can you offer to others?')),
                ('availability', models.JSONField(blank=True, default=list, help_text='List of availability slots')),
                ('photo_url', models.URLField(blank=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('is_sponsor_eligible', models.BooleanField(default=False, help_text='Eligible for sponsorship pool subsidy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
