# Generated by Django 6.0.2 on 2026-03-03 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('category', models.CharField(choices=[('childcare', 'Childcare'), ('cooking', 'Cooking / Meal Prep'), ('cleaning', 'Cleaning / Household'), ('tutoring', 'Tutoring / Homework'), ('transportation', 'Transportation'), ('errands', 'Errands'), ('emotional', 'Emotional Support'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('confirmed_by_receiver', models.BooleanField(default=False)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_given', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
