# Generated by Django 6.0.2 on 2026-03-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(blank=True, max_length=150)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(choices=[('founding_member', 'Founding Member — $25'), ('patron', 'Village Patron — $50'), ('champion', 'Village Champion — $100'), ('builder', 'Village Builder — $250')], max_length=20)),
                ('zeffy_reference', models.CharField(blank=True, max_length=100)),
                ('is_sponsorship', models.BooleanField(default=False, help_text='Funds go to sponsorship pool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
