# Generated by Django 6.0.2 on 2026-03-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('kids_ages', models.CharField(help_text='Comma-separated ages, e.g. 3, 7, 11', max_length=100)),
                ('needs', models.TextField(blank=True, help_text='What kind of help do you need?')),
                ('offers', models.TextField(blank=True, help_text='What can you offer to others?')),
                ('chapter', models.CharField(choices=[('houston', 'Houston'), ('austin', 'Austin'), ('dallas', 'Dallas')], default='houston', max_length=20)),
                ('source', models.CharField(default='website', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
