# Generated by Django 6.0.2 on 2026-03-03 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, help_text='For anonymous feedback', max_length=254)),
                ('text', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('safety', 'Safety Concern'), ('ux', 'UX / Design'), ('praise', 'Praise / Testimonial'), ('other', 'Other')], default='other', max_length=20)),
                ('ai_category', models.CharField(blank=True, choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('safety', 'Safety Concern'), ('ux', 'UX / Design'), ('praise', 'Praise / Testimonial'), ('other', 'Other')], help_text='Auto-categorized by AI', max_length=20)),
                ('ai_summary', models.CharField(blank=True, help_text='AI one-line summary', max_length=200)),
                ('ai_priority', models.IntegerField(default=0, help_text='AI-assessed priority 1-5 (5=urgent)')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('done', 'Done'), ('wont_fix', "Won't Fix")], default='new', max_length=10)),
                ('upvotes', models.IntegerField(default=0)),
                ('source', models.CharField(default='app', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ai_priority', '-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedbackitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feedback')},
            },
        ),
    ]
